export const RECEIVE_MOVIES = "RECEIVE_MOVIES";
export const RECEIVE_LOGIN_STATUS = "RECEIVE_LOGIN_STATUS";
export const RECEIVE_FB_SDK = "RECEIVE_FB_SDK";
export const LOGOUT = "LOGOUT";
export const RECEIVE_PAGES = "RECEIVE_PAGES";
export const RECEIVE_PAGE = "RECEIVE_PAGE";
export const RECEIVE_PAGE_FEED = "RECEIVE_PAGE_FEED";
export const RECEIVE_UNPUBLISHED_POSTS = "RECEIVE_UNPUBLISHED_POSTS";
